### ISSUE TITLE
Unhide the Requester's name

### ISSUE THREAD

**Issue by awoegno** [Anveio/mturk-engine#18]
Last question:

On the Account page, the Requester's name is hidden:

https://postimg.org/image/cw8buho7f/

Each HIT has to be clicked on in order to find the Requester I am looking for. Which is a lot of clicking if you have done a lot of HITS. Are you able to put the Requester's name on the same line as the dollar amount and HIT name?

Also, 

Am I able to reorder the completed HITS so I can see them in the order they are completed, instead of in the order of the amount? The same way it is ordered in Mturk. 

Thank you so much for your help!

**Comment by Anveio** [comment]
This is actually in the 1.5.0 update https://github.com/Anveio/mturk-engine/releases/tag/1.5.0 . Requester names are now visible at a glance on the right. Their names are still provided for highlighting purposes after expanding a HIT. 

Reordering HITs is a little more complicated but for the next update I'm focusing on building a way to search for specific HITs in your database, so that feature will likely come then.

**Comment by Anveio** [comment]
The database search feature added in the 1.8.0 update allows you to reorder your HITs. Feel free to open another issue if you have further suggestions.
