### ISSUE TITLE
Suggestions for blocklist

### ISSUE THREAD

**Issue by kimadagem** [Anveio/mturk-engine#23]
I've watched the instruction GIF & tried it myself but I don't see a way to block a requester, just individual hits. It would really help me to have the search feature avoid all hits from a particular requester. Also, if you can do that I would like a way to import my own blocklist into it. Right now it exists in Hit Scraper but I also have it saved in a spreadsheet, so I can format it in different ways for compatibility. My requester blocklist is very large (I have 4 years' worth of blocks :) ) and this would be a lot more efficient than trying to catch their hits as they show up on Search, which is really prone to error.

Also - I just spent time blocking a whole lot of hits about recording a video of yourself at a particular time. It would be nice to have a wildcard for those kinds of hits so I don't have to take the time to block them individually.

And finally - I don't see a way to clear the blocklist, either individually by hit or as a whole. I clear hit titles (not requesters) from my own Hit Scraper list every week to keep it from getting too big (I use date separators); I'm afraid that might slow down the search plus, I don't necessarily want to block a hit permanently. Your list seems to keep the requester name and the hit title together, which would at least avoid the problem of missing a hit with the same title from a different requester.

About blocking just a requester - the MTurk Suite developer told me he's using requester IDs rather than names. That's a great idea, because it will catch requester name changes, which the Scaper blocklist doesn't do (and it's probably why my list there is so large). If you can find a way to implement requester blocking by ID rather than name I think it would be a much more efficient way to do it.

Thank you.

**Comment by Anveio** [comment]
Thanks for these suggestions @kimadagem. To block a requester, click on any search result to expand it (just like on the Worker Mturk website), and you should see a "Block Requester" button in red. Click that in order to block a requester.

All blocks are done by group ID (for HITs) and requester ID (for requesters). You don't have to worry about a large blocklist slowing search in Mturk Engine. 

Blocking keywords and deleting multiple entries from blocklists at a time is on my radar for a future update, but importing a blocklist from other programs isn't. Many versions of HitScraper did not use groupID or requesterIds, so it would be impossible to import a blocklist entry from that. Even if newer versions or other scripts did use IDs I can't spend the development time supporting other peoples' programs because then bugs or even minor changes in their implementation of a block list could mean buggy behavior in Mturk Engine.

**Comment by Anveio** [comment]
Deleting multiple entries from blocklists landed in v1.7.0. I'll continue to improve it further as I brainstorm ideas to make browsing very large blocklists feasible. 

Feel free to open another issue if you run into a bug with this feature.
