### ISSUE TITLE
HIT Searching stopped automatically & Getting error Your search returned no results. Make sure you're logged in and check your search settings.

### ISSUE THREAD

**Issue by princeJoelMathew** [Anveio/mturk-engine#27]
# Issue summary

Thanks for submitting an issue to Mturk Engine. Use this space to provide a high-level summary of the problem or feature request:

## Expected behavior

When the problem occurs, what do you think should have happened? If the issue is a feature request, what would you like to see?

## Actual behavior

What actually happened? Include any error messages you see in the console when the issue occurs (press F12 while using Mturk Engine to see the console).

## Steps to Reproduce the Problem

1. 2. 3.

## Specifications

* Mturk Engine version:
* Browser:

**Comment by Anveio** [comment]
Thanks for posting this issue @princeJoelMathew but I'm not sure exactly what the issue is. If your search is returning no results make sure your search settings aren't something that would return 0 results (for example a minimum reward of $100). If you mean you don't like that continuous searching stops automatically after a search that returns 0 results, I agree with you and it'll be removed in 1.7.0.

**Comment by princeJoelMathew** [comment]
Thanks Anveio..
