### ISSUE TITLE
Searching HIT not working properly past few days

### ISSUE THREAD

**Issue by princeJoelMathew** [Anveio/mturk-engine#29]
# Issue summary

Past few days I am facing issues that Searching HIT is not working properly & Need your support for below issues.

1.  Need your support to search the HIT immediate. Even I selected Time Between Searches 1 Min. 
Most of HIT is missing but the same time missing HITs are captured in MTurk Suite(HIT Finder). 

2.  Enable desktop notifications is not working properly. HIT is notify sometimes only.. The giving option is not happened (A link to accept an unread HIT will be sent to your desktop with your permission. You can revoke permission at any time.)

3. After using your Mturk Engine Script I removed major HIT finder & Catcher scripts..So awaiting your valuable response & Next updated Mturk engine version. 

Note : I am using updated Firefox browser & Mturk engine version. 

With Regards
S.Prince

**Comment by Anveio** [comment]
Hi @princeJoelMathew. If the problem is too many HITs are being hidden, I'd recommend double checking your Turkopticon settings. 

I'm not sure what could be causing notifications to only be sent sometimes. Make sure the minimum notification reward amount isn't set too high and that the page has permission to send you notifications (you can check with the 'Request permission' button). If that doesn't fix it I'll need a detailed series of steps to reproduce the bug in order to investigate it further.

**Comment by princeJoelMathew** [comment]
Thanks for your instruction.. 

1.  I am disable the Turkopticon setting & Also set the zero value of  Turkopticon attribute score weights. 
2. I agreed your point but I am getting less notification alert after mentioning value of reward amount is $1 
3. We are waiting to expect your next mturk engine updated version. When you will release next version ?

With Regards
S.Prince 
![snap 2018-04-30 at 11 29 22](https://user-images.githubusercontent.com/35998240/39416332-c45ad584-4c69-11e8-87c0-26a3c82f5b27.jpg)

**Comment by Anveio** [comment]
I was unable to reproduce this issue @princeJoelMathew. If the issue persists in the new update feel free to open another issue with steps to help me track down this bug.

**Comment by princeJoelMathew** [comment]
Ok Thanks Anveio..
