### ISSUE TITLE
Getting Error msg immediate after starting watcher

### ISSUE THREAD

**Issue by princeJoelMathew** [Anveio/mturk-engine#31]
![snap 2018-05-04 at 18 32 34](https://user-images.githubusercontent.com/35998240/39629376-9eb1ebfc-4fc9-11e8-8e6a-ec5aae1a9e2a.jpg)
Hi, I am getting Error msg immediate after starting watcher 

" in 1:45-2 hours" has sent too many requests to MTurk and has been automatically stopped."

Hope I am facing issues after updating the mturk engine. Please do the needful.

## Specifications

* Mturk Engine version: 1.7.0
* Browser: Firefox 59.0.3 (64-bit)

**Comment by princeJoelMathew** [comment]
Hope old version is better for me 1.6.2.. So please share me How to degrade the version from 1.7.0 to 1.6.2?

Unable to catch the Hit through desktop notifications but earlier It got easily max hit which showing desktop notification ...

Please do the needful

**Comment by Anveio** [comment]
This is actually intended behavior if a watcher runs into a 429 response from Mturk, which is caused when you've made too many requests (usually because too many watchers are running or because a watcher has too low of a delay).

If you think this is being caused because of something else, feel free to reopen this issue.
